apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-App
  namespace: monitoring
  labels:
    app: 'app-monitor'
spec:
  selector:
    matchLabels:
      monitor: "true"
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - default